### ISSUE TITLE
Hardware diagram

### ISSUE THREAD

**Issue by mozts2005** [martinwoodward/DasDeployer#3]
Any update on the hardware diagram/images?

**Comment by mozts2005** [comment]
I would love to help with this project, but I am new to working with hardware anything I can do to have you post images of the hardware? 
I will convert them to a diagram. Then provide a write up of my putting the parts together.

**Comment by martinwoodward** [comment]
Fixed with https://github.com/martinwoodward/DasDeployer/commit/d582e61090dcb551ac72efad37375552bf6ff200
