### ISSUE TITLE
Questions I'm having as I go through this build

### ISSUE THREAD

**Issue by FISHMANPET** [martinwoodward/DasDeployer#4]
Martin suggested on Twitter I open this up as an issue to track and for other people to see them as well.

~I'm not sure exactly how the Pi is being powered.  I'm not sure if you're running a +5v from the PSU to the 5v HAT pin on the Pi, or running the +5v into your perfboard, and letting 3.3V to 5V shifter board convert that to 3.3V to power the Pi, or both?  Looking at the pictures from the Ignite presentation (Slide 21) it looks like there are a couple of wires going into the PSU and (other than the mains input) they all look to be on the 5V terminals, but I can't tell from the picture where they all go or even if they're all being used.  It also looks like no matter what there's +5v going into the perfboard but no ground coming out, so it's being grounded via the Pi, so the Pi has to be connected to the ground on the PSU from somewhere?~ I've been able to power the Pi by plugging the +5v and ground from my PSU into the 5V and Ground pins on the Pi respectively.  My understanding on the 5V rail on the Pi is that all the 5V is connected, so once you're running power into the 5V of the Pi, the "external" 5V going into the perf board can either come directly from the PSU or from the other 5V pin on the Pi, electrically there appears to be no difference.

~Another question with the Toggle switches, I thought this would be relatively simple and I'd be able to figure it out myself and I mostly did, but apparently these switches are pretty common and also not well documented, so lots of people smarter than me have had some problems with them.  I went with a different model than what was recommended but it looks like the leads are labelled the same way.  I attached the top lead with the ground symbol to a ground terminal, the positive lead to IO12 (the "dev" switch led in the code) and the remaining lead (looks like a headlight? I can't find any reference for what that symbol means) to IO16 (the "dev" toggle in the code).  Once I had it wired up, I was able to go to a Python terminal and initialize IO12 as a light and turn it on and off (once I'd put the switch in the On position) and initialize IO16 as a button and read when it was pressed (flipped on) and released (flipped off).  Though somehow when it was flipped off there LED was faintly on, though not as bright as when the switch was flipped on and the LED properly turned on.  As if a little bit of current was flowing through from the switch detection.  So I'm wondering if your switches are faintly lit when they're off, or if I reversed IO12 and IO16, or if the code is dealing with this condition somehow?~ Played with this again, I was right that the positive terminal goes to 12 and the lamp terminal goes to 16, and I see in the code that you initialize the switch with the pull_up off, which prevents the faint glow even when the LED is off.

**Comment by FISHMANPET** [comment]
~Also related to power, looking at your pictures from your presentation it looks like you're basically wiring all the ground terminals together for the LCD, toggles, and buttons, and then off to somewhere (into the ground terminal on the PSU)?~

~Your slide 22 has a picture of most of the wiring, but the toggle switches are only ground.  I think a picture of the assembled backside with the Pi's terminal block visible would be really useful, to get a good idea of where all the wires go.~ 

Having played around with this enough  I think I've got a good sense of how this works.

Ground for the LCD, toggles, and the switch ground for the buttons (C) can go into any ground (I may segregate 5V and 3.3V ground for my final build but for now it's all going to the same channel on my breadboard).  Ground for the LED on the buttons (-) goes into middle pin of the Mosfet, and the + of the LED is wired directly to the 5V from the PSU.

**Comment by FISHMANPET** [comment]
Another thing I'm curious about is why you've put the button LED signals through the shifter to shift them to 5V before going into the source on the mosfet.  I've looked at the specs for the mosfet you recomendded (with some help from other people smarter than me) and especially because the overall amperage is so low, the 3.3V signal directly out of the GPIO is sufficient to trigger the LED, without having to first be shifted to 5V.  I wired up the equivalent of the diagram below, and with the LEDs enabled the voltage and amperage was the same whether the source signal was 3.3V or 5.5V.  But before I solder things in like that I want to make sure there's a reason you did this that I'm missing.

![circuit (1)](https://user-images.githubusercontent.com/7810151/73426661-8a6edd00-42fa-11ea-9862-ed59f496d6df.png)

**Comment by martinwoodward** [comment]
Sorry for sucking in my response time.

I'm actually powering the LED lights in the pushbuttons using the MOSFETS as they needed more current at 5v than simply stepping up the signal allowed. Originally I thought I was going to be driving them off 12v from the arcade power supply but then the buttons ended up being too bright and would drown out the other LED's in photos.
